/* length.c */

/* generated by GNU MARST -- Algol-to-C Translator, Version 2.2 */

#include "algol.h"

extern struct desc length_0 /* precompiled integer procedure */
(     struct arg /* str: by name string */
);

struct dsa_length_0
{     /* procedure length (level 0) declared at line 26 */
      char *proc;
      char *file;
      int line;
      struct dsa *parent;
      struct dsa *vector[0+1];
      /* level of innermost block = 1 */
      struct mem *old_top_0;
      struct mem *new_top_0;
      struct mem *old_top_1;
      struct mem *new_top_1;
      /* procedure block 1 (level 0) beginning at line 26 */
      struct desc retval;
      /* str: by name string
         specified at line 27 and never referenced */
      char *str_1;
      /* local block 2 (level 1) beginning at line 28 */
};

struct desc length_0 /* precompiled integer procedure */
(     struct arg str_1 /* by name string */
)
{     struct dsa_length_0 my_dsa;
      register struct dsa_length_0 *dsa_0 = &my_dsa;
      my_dsa.proc = "length";
      my_dsa.file = "length.alg";
      my_dsa.line = 26;
      my_dsa.parent = active_dsa, active_dsa = (struct dsa *)&my_dsa;
      my_dsa.vector[0] = (void *)dsa_0;
      /* start of procedure block 1 (level 0) at line 26 */
      dsa_0->old_top_0 = stack_top;
      my_dsa.str_1 = str_1.arg1;
      dsa_0->new_top_0 = stack_top;
      /* start of local block 2 (level 1) at line 28 */
      dsa_0->old_top_1 = stack_top;
      dsa_0->new_top_1 = stack_top;
      dsa_0->line = 28;
      /* inline code */
      my_dsa.retval.u.int_val = strlen(my_dsa.str_1);
      pop_stack(dsa_0->old_top_1);
      /* end of block 2 */
      pop_stack(dsa_0->old_top_0);
      /* end of block 1 */
      my_dsa.retval.lval = 0;
      my_dsa.retval.type = 'i';
      active_dsa = my_dsa.parent;
      return my_dsa.retval;
}

/* eof */
