/* maxint.c */

/* generated by GNU MARST -- Algol-to-C Translator, Version 2.2 */

#include "algol.h"

extern struct desc maxint_0 /* precompiled integer procedure */ (void);

struct dsa_maxint_0
{     /* procedure maxint (level 0) declared at line 26 */
      char *proc;
      char *file;
      int line;
      struct dsa *parent;
      struct dsa *vector[0+1];
      /* level of innermost block = 1 */
      struct mem *old_top_0;
      struct mem *new_top_0;
      struct mem *old_top_1;
      struct mem *new_top_1;
      /* procedure block 1 (level 0) beginning at line 26 */
      struct desc retval;
      /* local block 2 (level 1) beginning at line 27 */
};

struct desc maxint_0 /* precompiled integer procedure */ (void)
{     struct dsa_maxint_0 my_dsa;
      register struct dsa_maxint_0 *dsa_0 = &my_dsa;
      my_dsa.proc = "maxint";
      my_dsa.file = "maxint.alg";
      my_dsa.line = 26;
      my_dsa.parent = active_dsa, active_dsa = (struct dsa *)&my_dsa;
      my_dsa.vector[0] = (void *)dsa_0;
      /* start of procedure block 1 (level 0) at line 26 */
      dsa_0->old_top_0 = stack_top;
      dsa_0->new_top_0 = stack_top;
      /* start of local block 2 (level 1) at line 27 */
      dsa_0->old_top_1 = stack_top;
      dsa_0->new_top_1 = stack_top;
      dsa_0->line = 27;
      /* inline code */
      my_dsa.retval.u.int_val = INT_MAX;
      pop_stack(dsa_0->old_top_1);
      /* end of block 2 */
      pop_stack(dsa_0->old_top_0);
      /* end of block 1 */
      my_dsa.retval.lval = 0;
      my_dsa.retval.type = 'i';
      active_dsa = my_dsa.parent;
      return my_dsa.retval;
}

/* eof */
