/* (stdout) */

/* generated by GNU MARST -- Algol-to-C Translator, Version 2.2 */
/* Fri Apr 25 13:07:37 2003 */
/* source file: acm11.alg */
/* object file: (stdout) */

#include "algol.h"

extern struct desc main_program_0 /* program */ (void);

static struct desc He_3 /* local real procedure */
(     struct arg /* n: by name integer */,
      struct arg /* X: by name real */
);

extern struct desc outreal_0 /* builtin void procedure */
(     struct arg /* channel: by value integer */,
      struct arg /* re: by value real */
);

extern struct desc outstring_0 /* builtin void procedure */
(     struct arg /* channel: by value integer */,
      struct arg /* str: by name string */
);

struct dsa_main_program_0
{     /* procedure main_program (level 0) declared at line 1 */
      char *proc;
      char *file;
      int line;
      struct dsa *parent;
      struct dsa *vector[0+1];
      /* level of innermost block = 2 */
      struct mem *old_top_0;
      struct mem *new_top_0;
      struct mem *old_top_1;
      struct mem *new_top_1;
      struct mem *old_top_2;
      struct mem *new_top_2;
      /* procedure block 1 (level 0) beginning at line 1 */
      struct desc retval;
      /* local block 2 (level 1) beginning at line 1 */
      /* local block 3 (level 2) beginning at line 17 */
      /* He: real procedure
         declared at line 17 and first referenced at line 36 */
};

struct dsa_He_3
{     /* procedure He (level 1) declared at line 17 */
      char *proc;
      char *file;
      int line;
      struct dsa *parent;
      struct dsa *vector[1+1];
      /* level of innermost block = 3 */
      struct mem *old_top_0;
      struct mem *new_top_0;
      struct mem *old_top_1;
      struct mem *new_top_1;
      struct mem *old_top_2;
      struct mem *new_top_2;
      struct mem *old_top_3;
      struct mem *new_top_3;
      /* procedure block 4 (level 0) beginning at line 17 */
      struct desc retval;
      /* n: by name integer
         specified at line 18 and first referenced at line 26 */
      struct arg n_4;
      /* X: by name real
         specified at line 19 and first referenced at line 25 */
      struct arg X_4;
      /* local block 5 (level 1) beginning at line 20 */
      /* local block 6 (level 2) beginning at line 21 */
      /* a: real
         declared at line 21 and first referenced at line 24 */
      double a_6;
      /* b: real
         declared at line 21 and first referenced at line 25 */
      double b_6;
      /* c: real
         declared at line 21 and first referenced at line 27 */
      double c_6;
      /* i: integer
         declared at line 22 and first referenced at line 30 */
      int i_6;
      /* teta_r: real
         declared at line 30 and first referenced at line 30 */
      double teta_r_6;
      /* teta_i: integer
         declared at line 30 and first referenced at line 30 */
      int teta_i_6;
      /* local block 7 (level 3) beginning at line 30 */
};

static void _sigma_1(void)
{     /* statement following 'do' at line 30 */
      register struct dsa_He_3 *dsa_1 = (void *)global_dsa->vector[1];
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      /* start of local block 7 (level 3) at line 30 */
      dsa_1->old_top_3 = stack_top;
      dsa_1->new_top_3 = stack_top;
      dsa_1->line = 31;
      dsa_1->line = 32;
      dsa_1->c_6 = int2real(2) * get_real((global_dsa = dsa_1->X_4.arg2,
          (*(struct desc (*)(void))dsa_1->X_4.arg1)())) * dsa_1->b_6 - 
         int2real(2 * dsa_1->i_6) * dsa_1->a_6;
      dsa_1->line = 33;
      dsa_1->a_6 = dsa_1->b_6;
      dsa_1->line = 34;
      dsa_1->b_6 = dsa_1->c_6;
      pop_stack(dsa_1->old_top_3);
      /* end of block 7 */
      return;
}

struct desc He_3 /* local real procedure */
(     struct arg n_4 /* by name integer */,
      struct arg X_4 /* by name real */
)
{     struct dsa_He_3 my_dsa;
      register struct dsa_He_3 *dsa_1 = &my_dsa;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      my_dsa.proc = "He";
      my_dsa.file = "acm11.alg";
      my_dsa.line = 17;
      my_dsa.parent = active_dsa, active_dsa = (struct dsa *)&my_dsa;
      my_dsa.vector[0] = (void *)dsa_0;
      my_dsa.vector[1] = (void *)dsa_1;
      /* start of procedure block 4 (level 0) at line 17 */
      dsa_1->old_top_0 = stack_top;
      my_dsa.n_4 = n_4;
      my_dsa.X_4 = X_4;
      dsa_1->new_top_0 = stack_top;
      /* start of local block 5 (level 1) at line 20 */
      dsa_1->old_top_1 = stack_top;
      dsa_1->new_top_1 = stack_top;
      dsa_1->line = 20;
      /* start of local block 6 (level 2) at line 21 */
      dsa_1->old_top_2 = stack_top;
      dsa_1->new_top_2 = stack_top;
      dsa_1->line = 24;
      dsa_1->a_6 = int2real(1);
      dsa_1->line = 25;
      dsa_1->b_6 = int2real(2) * get_real((global_dsa = dsa_1->X_4.arg2,
          (*(struct desc (*)(void))dsa_1->X_4.arg1)()));
      dsa_1->line = 26;
      if (!(equal(get_int((global_dsa = dsa_1->n_4.arg2, (*(struct desc 
         (*)(void))dsa_1->n_4.arg1)())), 0))) goto _gamma_3;
      dsa_1->line = 27;
      dsa_1->c_6 = dsa_1->a_6;
      goto _omega_3;
_gamma_3:
      dsa_1->line = 28;
      if (!(equal(get_int((global_dsa = dsa_1->n_4.arg2, (*(struct desc 
         (*)(void))dsa_1->n_4.arg1)())), 1))) goto _gamma_2;
      dsa_1->line = 29;
      dsa_1->c_6 = dsa_1->b_6;
      goto _omega_2;
_gamma_2:
      dsa_1->line = 30;
      dsa_1->line = 30;
      dsa_1->i_6 = 1;
      dsa_1->teta_i_6 = 1;
_gamma_1:
      dsa_1->line = 30;
      if ((dsa_1->i_6 - (get_int((global_dsa = dsa_1->n_4.arg2, (*(
         struct desc (*)(void))dsa_1->n_4.arg1)())) - 1)) * (
         dsa_1->teta_i_6 < 0 ? -1 : dsa_1->teta_i_6 > 0 ? +1 : 0) > 0) 
         goto _omega_1;
      global_dsa = (void *)dsa_1, _sigma_1();
      dsa_1->i_6 = dsa_1->teta_i_6 + dsa_1->i_6;
      goto _gamma_1;
_omega_1: /* element exhausted */
_omega_2:
_omega_3:
      dsa_1->line = 36;
      dsa_1->retval.u.real_val = dsa_1->c_6;
      pop_stack(dsa_1->old_top_2);
      /* end of block 6 */
      pop_stack(dsa_1->old_top_1);
      /* end of block 5 */
      pop_stack(dsa_1->old_top_0);
      /* end of block 4 */
      my_dsa.retval.lval = 0;
      my_dsa.retval.type = 'r';
      active_dsa = my_dsa.parent;
      return my_dsa.retval;
}

static struct desc _thunk_1(void)
{     /* actual parameter at line 40 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 1;
      return res;
}

static struct desc _thunk_2(void)
{     /* actual parameter at line 40 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 3;
      return res;
}

static struct desc _thunk_3(void)
{     /* actual parameter at line 40 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = 2.5;
      return res;
}

static struct desc _thunk_4(void)
{     /* actual parameter at line 40 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 40;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, He_3(
         make_arg((void *)_thunk_2, dsa_0), make_arg((void *)_thunk_3, 
         dsa_0))));
      return res;
}

struct desc main_program_0 /* program */ (void)
{     struct dsa_main_program_0 my_dsa;
      register struct dsa_main_program_0 *dsa_0 = &my_dsa;
      my_dsa.proc = "main_program";
      my_dsa.file = "acm11.alg";
      my_dsa.line = 1;
      my_dsa.parent = active_dsa, active_dsa = (struct dsa *)&my_dsa;
      my_dsa.vector[0] = (void *)dsa_0;
      /* start of procedure block 1 (level 0) at line 1 */
      dsa_0->old_top_0 = stack_top;
      dsa_0->new_top_0 = stack_top;
      /* start of local block 2 (level 1) at line 1 */
      dsa_0->old_top_1 = stack_top;
      dsa_0->new_top_1 = stack_top;
      dsa_0->line = 1;
      /* start of local block 3 (level 2) at line 17 */
      dsa_0->old_top_2 = stack_top;
      dsa_0->new_top_2 = stack_top;
      dsa_0->line = 40;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_4, dsa_0))));
      dsa_0->line = 40;
      ((global_dsa = (void *)dsa_0, outstring_0(make_arg((void *)
         _thunk_1, dsa_0), make_arg("\n", NULL))));
      pop_stack(dsa_0->old_top_2);
      /* end of block 3 */
      pop_stack(dsa_0->old_top_1);
      /* end of block 2 */
      pop_stack(dsa_0->old_top_0);
      /* end of block 1 */
      my_dsa.retval.lval = 0;
      my_dsa.retval.type = 0;
      active_dsa = my_dsa.parent;
      return my_dsa.retval;
}

int main(void)
{     /* Algol program startup code */
      main_program_0();
      return 0;
}

/* eof */
