/* (stdout) */

/* generated by GNU MARST -- Algol-to-C Translator, Version 2.2 */
/* Fri Apr 25 12:54:57 2003 */
/* source file: acm10.alg */
/* object file: (stdout) */

#include "algol.h"

extern struct desc main_program_0 /* program */ (void);

static struct desc Ch_3 /* local real procedure */
(     struct arg /* n: by name integer */,
      struct arg /* X: by name real */
);

extern struct desc outreal_0 /* builtin void procedure */
(     struct arg /* channel: by value integer */,
      struct arg /* re: by value real */
);

extern struct desc outstring_0 /* builtin void procedure */
(     struct arg /* channel: by value integer */,
      struct arg /* str: by name string */
);

struct dsa_main_program_0
{     /* procedure main_program (level 0) declared at line 1 */
      char *proc;
      char *file;
      int line;
      struct dsa *parent;
      struct dsa *vector[0+1];
      /* level of innermost block = 2 */
      struct mem *old_top_0;
      struct mem *new_top_0;
      struct mem *old_top_1;
      struct mem *new_top_1;
      struct mem *old_top_2;
      struct mem *new_top_2;
      /* procedure block 1 (level 0) beginning at line 1 */
      struct desc retval;
      /* local block 2 (level 1) beginning at line 1 */
      /* local block 3 (level 2) beginning at line 8 */
      /* Ch: real procedure
         declared at line 8 and first referenced at line 27 */
};

struct dsa_Ch_3
{     /* procedure Ch (level 1) declared at line 8 */
      char *proc;
      char *file;
      int line;
      struct dsa *parent;
      struct dsa *vector[1+1];
      /* level of innermost block = 3 */
      struct mem *old_top_0;
      struct mem *new_top_0;
      struct mem *old_top_1;
      struct mem *new_top_1;
      struct mem *old_top_2;
      struct mem *new_top_2;
      struct mem *old_top_3;
      struct mem *new_top_3;
      /* procedure block 4 (level 0) beginning at line 8 */
      struct desc retval;
      /* n: by name integer
         specified at line 10 and first referenced at line 16 */
      struct arg n_4;
      /* X: by name real
         specified at line 9 and first referenced at line 15 */
      struct arg X_4;
      /* local block 5 (level 1) beginning at line 11 */
      /* local block 6 (level 2) beginning at line 12 */
      /* a: real
         declared at line 12 and first referenced at line 15 */
      double a_6;
      /* b: real
         declared at line 12 and first referenced at line 15 */
      double b_6;
      /* c: real
         declared at line 12 and first referenced at line 17 */
      double c_6;
      /* i: integer
         declared at line 13 and first referenced at line 21 */
      int i_6;
      /* teta_r: real
         declared at line 21 and first referenced at line 21 */
      double teta_r_6;
      /* teta_i: integer
         declared at line 21 and first referenced at line 21 */
      int teta_i_6;
      /* local block 7 (level 3) beginning at line 21 */
};

static void _sigma_1(void)
{     /* statement following 'do' at line 21 */
      register struct dsa_Ch_3 *dsa_1 = (void *)global_dsa->vector[1];
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      /* start of local block 7 (level 3) at line 21 */
      dsa_1->old_top_3 = stack_top;
      dsa_1->new_top_3 = stack_top;
      dsa_1->line = 22;
      dsa_1->line = 23;
      dsa_1->c_6 = int2real(2) * get_real((global_dsa = dsa_1->X_4.arg2,
          (*(struct desc (*)(void))dsa_1->X_4.arg1)())) * dsa_1->b_6 - 
         dsa_1->a_6;
      dsa_1->line = 24;
      dsa_1->a_6 = dsa_1->b_6;
      dsa_1->line = 25;
      dsa_1->b_6 = dsa_1->c_6;
      pop_stack(dsa_1->old_top_3);
      /* end of block 7 */
      return;
}

struct desc Ch_3 /* local real procedure */
(     struct arg n_4 /* by name integer */,
      struct arg X_4 /* by name real */
)
{     struct dsa_Ch_3 my_dsa;
      register struct dsa_Ch_3 *dsa_1 = &my_dsa;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      my_dsa.proc = "Ch";
      my_dsa.file = "acm10.alg";
      my_dsa.line = 8;
      my_dsa.parent = active_dsa, active_dsa = (struct dsa *)&my_dsa;
      my_dsa.vector[0] = (void *)dsa_0;
      my_dsa.vector[1] = (void *)dsa_1;
      /* start of procedure block 4 (level 0) at line 8 */
      dsa_1->old_top_0 = stack_top;
      my_dsa.n_4 = n_4;
      my_dsa.X_4 = X_4;
      dsa_1->new_top_0 = stack_top;
      /* start of local block 5 (level 1) at line 11 */
      dsa_1->old_top_1 = stack_top;
      dsa_1->new_top_1 = stack_top;
      dsa_1->line = 11;
      /* start of local block 6 (level 2) at line 12 */
      dsa_1->old_top_2 = stack_top;
      dsa_1->new_top_2 = stack_top;
      dsa_1->line = 15;
      dsa_1->a_6 = int2real(1);
      dsa_1->line = 15;
      dsa_1->b_6 = get_real((global_dsa = dsa_1->X_4.arg2, (*(struct 
         desc (*)(void))dsa_1->X_4.arg1)()));
      dsa_1->line = 16;
      if (!(equal(get_int((global_dsa = dsa_1->n_4.arg2, (*(struct desc 
         (*)(void))dsa_1->n_4.arg1)())), 0))) goto _gamma_3;
      dsa_1->line = 17;
      dsa_1->c_6 = dsa_1->a_6;
      goto _omega_3;
_gamma_3:
      dsa_1->line = 18;
      if (!(equal(get_int((global_dsa = dsa_1->n_4.arg2, (*(struct desc 
         (*)(void))dsa_1->n_4.arg1)())), 1))) goto _gamma_2;
      dsa_1->line = 19;
      dsa_1->c_6 = dsa_1->b_6;
      goto _omega_2;
_gamma_2:
      dsa_1->line = 21;
      dsa_1->line = 21;
      dsa_1->i_6 = 2;
      dsa_1->teta_i_6 = 1;
_gamma_1:
      dsa_1->line = 21;
      if ((dsa_1->i_6 - (get_int((global_dsa = dsa_1->n_4.arg2, (*(
         struct desc (*)(void))dsa_1->n_4.arg1)())))) * (
         dsa_1->teta_i_6 < 0 ? -1 : dsa_1->teta_i_6 > 0 ? +1 : 0) > 0) 
         goto _omega_1;
      global_dsa = (void *)dsa_1, _sigma_1();
      dsa_1->i_6 = dsa_1->teta_i_6 + dsa_1->i_6;
      goto _gamma_1;
_omega_1: /* element exhausted */
_omega_2:
_omega_3:
      dsa_1->line = 27;
      dsa_1->retval.u.real_val = dsa_1->c_6;
      pop_stack(dsa_1->old_top_2);
      /* end of block 6 */
      pop_stack(dsa_1->old_top_1);
      /* end of block 5 */
      pop_stack(dsa_1->old_top_0);
      /* end of block 4 */
      my_dsa.retval.lval = 0;
      my_dsa.retval.type = 'r';
      active_dsa = my_dsa.parent;
      return my_dsa.retval;
}

static struct desc _thunk_1(void)
{     /* actual parameter at line 30 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 1;
      return res;
}

static struct desc _thunk_2(void)
{     /* actual parameter at line 30 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 0;
      return res;
}

static struct desc _thunk_3(void)
{     /* actual parameter at line 30 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .01;
      return res;
}

static struct desc _thunk_4(void)
{     /* actual parameter at line 30 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 30;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_2, dsa_0), make_arg((void *)_thunk_3, 
         dsa_0))));
      return res;
}

static struct desc _thunk_5(void)
{     /* actual parameter at line 31 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .2;
      return res;
}

static struct desc _thunk_6(void)
{     /* actual parameter at line 31 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 31;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_2, dsa_0), make_arg((void *)_thunk_5, 
         dsa_0))));
      return res;
}

static struct desc _thunk_7(void)
{     /* actual parameter at line 32 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .7;
      return res;
}

static struct desc _thunk_8(void)
{     /* actual parameter at line 32 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 32;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_2, dsa_0), make_arg((void *)_thunk_7, 
         dsa_0))));
      return res;
}

static struct desc _thunk_9(void)
{     /* actual parameter at line 33 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = 1.3;
      return res;
}

static struct desc _thunk_10(void)
{     /* actual parameter at line 33 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 33;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_2, dsa_0), make_arg((void *)_thunk_9, 
         dsa_0))));
      return res;
}

static struct desc _thunk_11(void)
{     /* actual parameter at line 36 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .01;
      return res;
}

static struct desc _thunk_12(void)
{     /* actual parameter at line 36 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 36;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_1, dsa_0), make_arg((void *)_thunk_11, 
         dsa_0))));
      return res;
}

static struct desc _thunk_13(void)
{     /* actual parameter at line 37 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .2;
      return res;
}

static struct desc _thunk_14(void)
{     /* actual parameter at line 37 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 37;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_1, dsa_0), make_arg((void *)_thunk_13, 
         dsa_0))));
      return res;
}

static struct desc _thunk_15(void)
{     /* actual parameter at line 38 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .7;
      return res;
}

static struct desc _thunk_16(void)
{     /* actual parameter at line 38 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 38;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_1, dsa_0), make_arg((void *)_thunk_15, 
         dsa_0))));
      return res;
}

static struct desc _thunk_17(void)
{     /* actual parameter at line 39 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = 1.3;
      return res;
}

static struct desc _thunk_18(void)
{     /* actual parameter at line 39 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 39;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_1, dsa_0), make_arg((void *)_thunk_17, 
         dsa_0))));
      return res;
}

static struct desc _thunk_19(void)
{     /* actual parameter at line 42 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 4;
      return res;
}

static struct desc _thunk_20(void)
{     /* actual parameter at line 42 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .01;
      return res;
}

static struct desc _thunk_21(void)
{     /* actual parameter at line 42 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 42;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_19, dsa_0), make_arg((void *)_thunk_20,
          dsa_0))));
      return res;
}

static struct desc _thunk_22(void)
{     /* actual parameter at line 43 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 4;
      return res;
}

static struct desc _thunk_23(void)
{     /* actual parameter at line 43 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .2;
      return res;
}

static struct desc _thunk_24(void)
{     /* actual parameter at line 43 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 43;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_22, dsa_0), make_arg((void *)_thunk_23,
          dsa_0))));
      return res;
}

static struct desc _thunk_25(void)
{     /* actual parameter at line 44 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 4;
      return res;
}

static struct desc _thunk_26(void)
{     /* actual parameter at line 44 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .7;
      return res;
}

static struct desc _thunk_27(void)
{     /* actual parameter at line 44 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 44;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_25, dsa_0), make_arg((void *)_thunk_26,
          dsa_0))));
      return res;
}

static struct desc _thunk_28(void)
{     /* actual parameter at line 45 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 4;
      return res;
}

static struct desc _thunk_29(void)
{     /* actual parameter at line 45 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = 1.3;
      return res;
}

static struct desc _thunk_30(void)
{     /* actual parameter at line 45 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 45;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_28, dsa_0), make_arg((void *)_thunk_29,
          dsa_0))));
      return res;
}

static struct desc _thunk_31(void)
{     /* actual parameter at line 48 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 8;
      return res;
}

static struct desc _thunk_32(void)
{     /* actual parameter at line 48 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .01;
      return res;
}

static struct desc _thunk_33(void)
{     /* actual parameter at line 48 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 48;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_31, dsa_0), make_arg((void *)_thunk_32,
          dsa_0))));
      return res;
}

static struct desc _thunk_34(void)
{     /* actual parameter at line 49 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 8;
      return res;
}

static struct desc _thunk_35(void)
{     /* actual parameter at line 49 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .2;
      return res;
}

static struct desc _thunk_36(void)
{     /* actual parameter at line 49 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 49;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_34, dsa_0), make_arg((void *)_thunk_35,
          dsa_0))));
      return res;
}

static struct desc _thunk_37(void)
{     /* actual parameter at line 50 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 8;
      return res;
}

static struct desc _thunk_38(void)
{     /* actual parameter at line 50 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = .7;
      return res;
}

static struct desc _thunk_39(void)
{     /* actual parameter at line 50 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 50;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_37, dsa_0), make_arg((void *)_thunk_38,
          dsa_0))));
      return res;
}

static struct desc _thunk_40(void)
{     /* actual parameter at line 51 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 8;
      return res;
}

static struct desc _thunk_41(void)
{     /* actual parameter at line 51 */
      struct desc res;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = 1.3;
      return res;
}

static struct desc _thunk_42(void)
{     /* actual parameter at line 51 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 51;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, Ch_3(
         make_arg((void *)_thunk_40, dsa_0), make_arg((void *)_thunk_41,
          dsa_0))));
      return res;
}

struct desc main_program_0 /* program */ (void)
{     struct dsa_main_program_0 my_dsa;
      register struct dsa_main_program_0 *dsa_0 = &my_dsa;
      my_dsa.proc = "main_program";
      my_dsa.file = "acm10.alg";
      my_dsa.line = 1;
      my_dsa.parent = active_dsa, active_dsa = (struct dsa *)&my_dsa;
      my_dsa.vector[0] = (void *)dsa_0;
      /* start of procedure block 1 (level 0) at line 1 */
      dsa_0->old_top_0 = stack_top;
      dsa_0->new_top_0 = stack_top;
      /* start of local block 2 (level 1) at line 1 */
      dsa_0->old_top_1 = stack_top;
      dsa_0->new_top_1 = stack_top;
      dsa_0->line = 1;
      /* start of local block 3 (level 2) at line 8 */
      dsa_0->old_top_2 = stack_top;
      dsa_0->new_top_2 = stack_top;
      dsa_0->line = 30;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_4, dsa_0))));
      dsa_0->line = 31;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_6, dsa_0))));
      dsa_0->line = 32;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_8, dsa_0))));
      dsa_0->line = 33;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_10, dsa_0))));
      dsa_0->line = 34;
      ((global_dsa = (void *)dsa_0, outstring_0(make_arg((void *)
         _thunk_1, dsa_0), make_arg("\n", NULL))));
      dsa_0->line = 36;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_12, dsa_0))));
      dsa_0->line = 37;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_14, dsa_0))));
      dsa_0->line = 38;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_16, dsa_0))));
      dsa_0->line = 39;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_18, dsa_0))));
      dsa_0->line = 40;
      ((global_dsa = (void *)dsa_0, outstring_0(make_arg((void *)
         _thunk_1, dsa_0), make_arg("\n", NULL))));
      dsa_0->line = 42;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_21, dsa_0))));
      dsa_0->line = 43;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_24, dsa_0))));
      dsa_0->line = 44;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_27, dsa_0))));
      dsa_0->line = 45;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_30, dsa_0))));
      dsa_0->line = 46;
      ((global_dsa = (void *)dsa_0, outstring_0(make_arg((void *)
         _thunk_1, dsa_0), make_arg("\n", NULL))));
      dsa_0->line = 48;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_33, dsa_0))));
      dsa_0->line = 49;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_36, dsa_0))));
      dsa_0->line = 50;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_39, dsa_0))));
      dsa_0->line = 51;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_1,
          dsa_0), make_arg((void *)_thunk_42, dsa_0))));
      dsa_0->line = 52;
      ((global_dsa = (void *)dsa_0, outstring_0(make_arg((void *)
         _thunk_1, dsa_0), make_arg("\n", NULL))));
      dsa_0->line = 54;
      /* <dummy statement> */;
      pop_stack(dsa_0->old_top_2);
      /* end of block 3 */
      pop_stack(dsa_0->old_top_1);
      /* end of block 2 */
      pop_stack(dsa_0->old_top_0);
      /* end of block 1 */
      my_dsa.retval.lval = 0;
      my_dsa.retval.type = 0;
      active_dsa = my_dsa.parent;
      return my_dsa.retval;
}

int main(void)
{     /* Algol program startup code */
      main_program_0();
      return 0;
}

/* eof */
