/* (stdout) */

/* generated by GNU MARST -- Algol-to-C Translator, Version 2.2 */
/* Fri Apr 25 13:14:54 2003 */
/* source file: acm33.alg */
/* object file: (stdout) */

#include "algol.h"

extern struct desc main_program_0 /* program */ (void);

static struct desc Factorial_3 /* local real procedure */
(     struct arg /* n: by value integer */
);

extern struct desc outreal_0 /* builtin void procedure */
(     struct arg /* channel: by value integer */,
      struct arg /* re: by value real */
);

extern struct desc outstring_0 /* builtin void procedure */
(     struct arg /* channel: by value integer */,
      struct arg /* str: by name string */
);

struct dsa_main_program_0
{     /* procedure main_program (level 0) declared at line 1 */
      char *proc;
      char *file;
      int line;
      struct dsa *parent;
      struct dsa *vector[0+1];
      /* level of innermost block = 2 */
      struct mem *old_top_0;
      struct mem *new_top_0;
      struct mem *old_top_1;
      struct mem *new_top_1;
      struct mem *old_top_2;
      struct mem *new_top_2;
      /* procedure block 1 (level 0) beginning at line 1 */
      struct desc retval;
      /* local block 2 (level 1) beginning at line 1 */
      /* local block 3 (level 2) beginning at line 7 */
      /* Factorial: real procedure
         declared at line 7 and first referenced at line 13 */
};

struct dsa_Factorial_3
{     /* procedure Factorial (level 1) declared at line 7 */
      char *proc;
      char *file;
      int line;
      struct dsa *parent;
      struct dsa *vector[1+1];
      /* level of innermost block = 1 */
      struct mem *old_top_0;
      struct mem *new_top_0;
      struct mem *old_top_1;
      struct mem *new_top_1;
      /* procedure block 4 (level 0) beginning at line 7 */
      struct desc retval;
      /* n: by value integer
         specified at line 9 and first referenced at line 13 */
      int n_4;
      /* local block 5 (level 1) beginning at line 12 */
};

static struct desc _thunk_1(void)
{     /* actual parameter at line 13 */
      struct desc res;
      register struct dsa_Factorial_3 *dsa_1 = (void *)
         global_dsa->vector[1];
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_1->line = 13;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = dsa_1->n_4 - 1;
      return res;
}

struct desc Factorial_3 /* local real procedure */
(     struct arg n_4 /* by value integer */
)
{     struct dsa_Factorial_3 my_dsa;
      register struct dsa_Factorial_3 *dsa_1 = &my_dsa;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      my_dsa.proc = "Factorial";
      my_dsa.file = "acm33.alg";
      my_dsa.line = 7;
      my_dsa.parent = active_dsa, active_dsa = (struct dsa *)&my_dsa;
      my_dsa.vector[0] = (void *)dsa_0;
      my_dsa.vector[1] = (void *)dsa_1;
      /* start of procedure block 4 (level 0) at line 7 */
      dsa_1->old_top_0 = stack_top;
      my_dsa.line = 9;
      my_dsa.n_4 = get_int((global_dsa = n_4.arg2, (*(struct desc (*)(
         void))n_4.arg1)()));
      dsa_1->new_top_0 = stack_top;
      /* start of local block 5 (level 1) at line 12 */
      dsa_1->old_top_1 = stack_top;
      dsa_1->new_top_1 = stack_top;
      dsa_1->line = 12;
      dsa_1->line = 13;
      dsa_1->retval.u.real_val = ((equal(dsa_1->n_4, 0)) ? (1.0) : (
         int2real(dsa_1->n_4) * get_real((global_dsa = (void *)dsa_1, 
         Factorial_3(make_arg((void *)_thunk_1, dsa_1))))));
      pop_stack(dsa_1->old_top_1);
      /* end of block 5 */
      pop_stack(dsa_1->old_top_0);
      /* end of block 4 */
      my_dsa.retval.lval = 0;
      my_dsa.retval.type = 'r';
      active_dsa = my_dsa.parent;
      return my_dsa.retval;
}

static struct desc _thunk_2(void)
{     /* actual parameter at line 16 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 1;
      return res;
}

static struct desc _thunk_3(void)
{     /* actual parameter at line 16 */
      struct desc res;
      res.lval = 0;
      res.type = 'i';
      res.u.int_val = 5;
      return res;
}

static struct desc _thunk_4(void)
{     /* actual parameter at line 16 */
      struct desc res;
      register struct dsa_main_program_0 *dsa_0 = (void *)
         global_dsa->vector[0];
      dsa_0->line = 16;
      res.lval = 0;
      res.type = 'r';
      res.u.real_val = get_real((global_dsa = (void *)dsa_0, 
         Factorial_3(make_arg((void *)_thunk_3, dsa_0))));
      return res;
}

struct desc main_program_0 /* program */ (void)
{     struct dsa_main_program_0 my_dsa;
      register struct dsa_main_program_0 *dsa_0 = &my_dsa;
      my_dsa.proc = "main_program";
      my_dsa.file = "acm33.alg";
      my_dsa.line = 1;
      my_dsa.parent = active_dsa, active_dsa = (struct dsa *)&my_dsa;
      my_dsa.vector[0] = (void *)dsa_0;
      /* start of procedure block 1 (level 0) at line 1 */
      dsa_0->old_top_0 = stack_top;
      dsa_0->new_top_0 = stack_top;
      /* start of local block 2 (level 1) at line 1 */
      dsa_0->old_top_1 = stack_top;
      dsa_0->new_top_1 = stack_top;
      dsa_0->line = 1;
      /* start of local block 3 (level 2) at line 7 */
      dsa_0->old_top_2 = stack_top;
      dsa_0->new_top_2 = stack_top;
      dsa_0->line = 16;
      ((global_dsa = (void *)dsa_0, outreal_0(make_arg((void *)_thunk_2,
          dsa_0), make_arg((void *)_thunk_4, dsa_0))));
      dsa_0->line = 17;
      ((global_dsa = (void *)dsa_0, outstring_0(make_arg((void *)
         _thunk_2, dsa_0), make_arg("\n", NULL))));
      pop_stack(dsa_0->old_top_2);
      /* end of block 3 */
      pop_stack(dsa_0->old_top_1);
      /* end of block 2 */
      pop_stack(dsa_0->old_top_0);
      /* end of block 1 */
      my_dsa.retval.lval = 0;
      my_dsa.retval.type = 0;
      active_dsa = my_dsa.parent;
      return my_dsa.retval;
}

int main(void)
{     /* Algol program startup code */
      main_program_0();
      return 0;
}

/* eof */
